// apps/react/src/App.tsx
import {
  Button,
  ThemeProvider,
  ThemeCustomizer,
  ThemeWrapper,
  TooltipProvider
} from "@shadcn-components/react"
import "shadcn-components/themes"
import 'shadcn-components/css'

function App() {
  return (
    <ThemeProvider defaultTheme="dark" storageKey="vite-ui-theme">
      <ThemeWrapper className="relative flex flex-col items-start md:flex-row md:items-center">
        <TooltipProvider>
          <ThemeCustomizer />
        </TooltipProvider>
      </ThemeWrapper>
      <ThemeWrapper>
        <Button>Hello</Button>
      </ThemeWrapper>
    </ThemeProvider>
  )
}

export default App

// apps/svelte/src/App.svelte
<script>
	import "./app.css"
	import {
		Button,
		CmdkDemo,
		ModeDropdown,
		ModeToggle,
		ThemeCustomizer,
		ThemeWrapper
	} from "@shadcn-components/svelte"
	// import "@shadcn-components/svelte/themes"
	import { ModeWatcher } from "mode-watcher"
</script>

<ModeWatcher />
<ThemeWrapper>
	<ThemeCustomizer />
	<Button>Hello</Button>
	<ModeToggle />
	<CmdkDemo class="h-[30em] w-[45em]" />
</ThemeWrapper>
